/*
 * script to execute on first page
 */

roadCover = new SET_DISPLAY();
roadCover._Set("#nav-main").navTab({"home":{"txt":"Home","icon":"icon-home","clss":"active"},"dealers":{"txt":"Dealers","icon":"icon-book","sub":["First Dealer","Second Dealer","Third Dealer","Fourth Dealer","hr","View All Dealers"]},"salesman":{"txt":"Salesman","icon":"icon-briefcase","sub":["First Salesman","Second Salesman","Third Salesman","Fourth Salesman","hr","View All Salesman"]},"customers":{txt:"Customers","icon":"icon-user"},"insurance":{"txt":"Insurance","icon":"icon-folder-open"},"system":{"txt":"System","icon":"icon-cog","sub":["View Logs","View Clients","Run Import","View Reports","Setup Permission"]}});
roadCover._Set({"addTo":"#tab-home section","clss":"btn btn-primary"}).btnGroup({"btn-notify":{"title":"My Notification","icon":"icon-inbox icon-white"},"btn-print":{"title":"Print Page","icon":"icon-print icon-white"},"btn-email":{"title":"Email page","icon":"icon-envelope icon-white"},"btn-word":{"title":"Convert to MS Word","icon":"icon-th-large icon-white"},"btn-excel":{"title":"Convert to MS Excel","icon":"icon-th icon-white"}});
roadCover.btnDropDown({"btn-user":{"clss":"btn btn-primary","href":"#","icon":"icon-user icon-white","txt":"User"},"btn-user-caret":{"clss":"btn btn-primary dropdown-toggle","href":"#","data-toggle":"dropdown","caret":"span"},"btn-sub-user-list":{"clss":"dropdown-menu","sub":{"profile-view":{"href":"#","icon":"icon-pencil","txt":"My profile"},"profile-new":{"href":"#","icon":"icon-plus","txt":"Create profile"},"profile-see":{"href":"#","icon":"icon-map-marker","txt":"Admin List"},"profile-div":{"divider":true},"profile-off":{"href":"#","icon":"icon-ban-circle","txt":"Logoff"}}}});
roadCover.btnCreation("button",{"name":"btn-help","clss":"btn btn-primary","title":"Help"},"","icon-question-sign icon-white");
roadCover.inputSearch({"div":{"clss":"btn-cust input-prepend pull-right"},"label":{"clss":"add-on","icon":"icon-search icon-white"},"input":{"clss":"input-medium search-all","name":"s","type":"text","placeholder":"Search page","form":"frm_search"}})
roadCover.pagiNation({"clss1":"pagination pull-right","clss2":"disabled","total":5,"link":"#home"});
roadCover._Set("#tab-dealers section").btnDropDown({"btn-dealer":{"clss":"btn btn-primary","href":"#","icon":"icon-book icon-white","txt":"All Dealers"},"btn-dealer-caret":{"clss":"btn btn-primary dropdown-toggle","href":"#","data-toggle":"dropdown","caret":"span"},"btn-sub-dealer-list":{"clss":"dropdown-menu","sub":{"dealer-one":{"href":"#","txt":"Dealer One"},"dealer-two":{"href":"#","txt":"Dealer Two"},"dealer-three":{"href":"#","txt":"Dealer Three"},"profile-div":{"divider":true},"dealer-all":{"href":"#","txt":"All Dealers"}}}});
roadCover.btnGroup({"btnListOn":{"title":"Display List","icon":"icon-list icon-white"},"btnListOff":{"title":"Remove List","icon":"icon-align-justify icon-white"},"btnList":{"title":"Return to List","icon":"icon-tasks icon-white"}});
roadCover.inputSearch({"div":{"clss":"btn-cust input-prepend pull-right"},"label":{"clss":"add-on","icon":"icon-search icon-white"},"input":{"clss":"input-medium search-dealer","name":"s","type":"text","placeholder":"Search page","form":"frm_search"}})
roadCover.setAddress({"Addr":{"txt":"79 Street, Suburb, City, Code, Country","title":"Physicall address","porp":"address","href":"http://maps.google.com/?q=79+Street,+Suburb,+City,+Code,+Country"},"Tel":{"txt":"(011) 808-9000","title":"Telephone Number","porp":"telephone","href":"tel:+27118089000"},"Fax":{"txt":"(011) 808-7000","title":"Fax Number","porp":"faxNumber","href":"tel:+27118087000"},"Email":{"txt":"namesurname@email.com","title":"Email address","porp":"email","href":"maito:namesurname@email.com"}});